export const LOGIN = 'LOGIN'     //登录页面;
export const SET_TOKEN = "SET_TOKEN" //设置token;
export const REMOVE_TOKEN = "REMOVE_TOKEN" //移除token;
export const SET_USER_INFO = "SET_USER_INFO" //设置用户信息；
export const SET_SECRET ="SET_SECRET"   //数据加密钥匙;
export const ROMOVE_SECRET = "ROMOVE_SECRET" //移除aes秘钥;
export const SOCKET_NEW_GUEST = 'SOCKET_NEW_GUEST' //socket保存新客到通知
export const SET_SHOP_LIST = "SET_SHOP_LIST" //设置管理商户列表
export const ROMOVE_SHOP_LIST = "ROMOVE_SHOP_LIST" //移除店铺列表
export const MAIN_INIT = "MAIN_INIT"    //主页初始化
export const USER_MANAGE_INIT = "USER_MANAGE_INIT" //用户管理页面初始化
export const CUT_SHOP_LIST_CURRENT = "CUT_SHOP_LIST_CURRENT" //全局切换店铺
export const SET_MAIN_VAL = "SET_MAIN_VAL"  // 设置初始化的时候值  
export const SET_NOTICE_TITLE = "SET_NOTICE_TITLE" //设置公共轮播值
export const SET_USER_CURRENT_INFO = "SET_USER_CURRENT_INFO" //当前用户的信息
export const GET_SET_SHOPINFO = "GET_SET_SHOPINFO" //得到门店信息
export const GET_NOTICE_ALLLIST="GET_NOTICE_ALLLIST" //得到全部公告列表
export const GET_SEARCH_USER="GET_SEARCH_USER"   //搜索页面得到搜索用户
export const GET_SEARCH_INDENT = "GET_SEARCH_INDENT"   //获取订单列表 
export const GET_NOTIFY_STATUS = "GET_NOTIFY_STATUS"   //获取消息的值